> library(TSA)
> setwd("c://temp//")
> options(digits=14)
> dat1 <- read.table("alfa-ag105(1).txt",header=T)
> head(dat1)
> attach(dat1)
> length(epo1)
> lepo=log(epo1)
> t <- 1:62
> model <- lm(epo1~t)
> summary(model)
> AIC(model)
> model1 <- lm(lepo~t)
> summary(model1)
> AIC(model1)
> fmod=fitted(model1)
> plot(t,lepo,xlab="index",ylab="ratio of the estimated SDFs",  type="l");lines(t,fmod,col="red")
> vt=resid(model1)
> write(vt,data("alfa-ag(1)vt.txt"),ncolumns=l)
> plot(t,vt,xlab="index",ylab="residuals",type="l")
> acf(vt,type="cor",lag.max=30,main="residuals for alfa-ag(1)",col= "red")
> pacf(vt,lag.max=30,main="residuals for alfa-ag(1) case",col="red")

