> library(TSA)
> setwd("c://temp//")
> options(digits=14)
> dat1 <- read.table("ag108_m30.txt",header=T)
> head(dat1)
> attach(dat1)
> dat2 <- read.table("gam108_m40.txt",header=T)
> head(dat2)
> attach(dat2)
> length(epo)
> length(epo1)
> epo2=epo/epo1
> lepo=log(epo2)
> t <- 1:108
> model <- lm(epo2~t+I(t^2)+I(t^3)+I(t^4))
> summary(model)
> AIC(model)
> model1 <- lm(lepo~t+I(t^2)+I(t^3)+I(t^4))
> summary(model1)
> AIC(model1)
> fmod=fitted(model1)
> plot(t,lepo,xlab="index",ylab="ln{ratio of the estimated SDFs}",  type="l");lines(t,fmod,col="red")
> vt=resid(model1)
> write(vt,data("gam-ag108vt.txt"),ncolumns=l)
> plot(t,vt,xlab="index",ylab="residuals",type="l")
> acf(vt,type="cor",lag.max=30,main="residuals for gam-ag108",col= "red")
> pacf(vt,lag.max=30,main="residuals for gam-ag108 case",col="red")
