> library(TSA)
> setwd("c://temp//")
> options(digits=14)
> dat1 <- read.table("ag105_m30.txt",header=T)
> head(dat1)
> attach(dat1)
> dat2 <- read.table("alfa105_m40.txt",header=T)
> head(dat2)
> attach(dat2)
> length(epo)
> length(epo1)
> epo2=epo/epo1
> lepo=log(epo2)
> t <- 1:105
> model <- lm(epo2~I(t^2))
> summary(model)
> AIC(model)
> model1 <- lm(lepo~I(t^2))
> summary(model1)
> AIC(model1)
> fmod=fitted(model)
> plot(t,epo2,xlab="index",ylab="ratio of the estimated SDFs",type="l");lines(t,fmod,col="red")
> vt=resid(model)
> write(vt,data("alfa-ag105lvt.txt"),ncolumns=1)
> plot(t,vt,xlab="index",ylab="residuals",type="l")
> acf(vt,type="cor",lag.max=30,main="residuals for alfa-ag105",col= "red")
> pacf(vt,lag.max=30,main="residuals for alfa-ag105 case",col="red")


