> library(TSA)
> setwd("c://temp//")
> options(digits=14)
> dat1 <- read.table("ag178_m30.txt",header=T)
> head(dat1)
> attach(dat1)
> dat2 <- read.table("alf178_m40.txt",header=T)
> head(dat2)
> attach(dat2)
> length(epo)
> length(epo1)
> epo2=epo/epo1
> lepo=log(epo2)
> t <- 1:178
> model <- lm(epo2~t+I(t^2)+I(t^3)+Ι(t^4))
> summary(model)
> AIC(model)
> model1 <- lm(lepo~t+I(t^2)+I(t^3)+Ι(t^4))
> AIC(model1)
> fmod=fitted(model1)
> plot(t,lepo,xlab="index",ylab="ln{ratio of the estimated SDFs}", type="l");lines(t,fmod,col="red")
> vt=resid(model1)
> write(vt,data("alf-ag178vt.txt"),ncolumns=l)
> plot(t,vt,xlab="index",ylab="residuals",type="l")
> acf(vt,type="cor",lag.max=30,main="residuals for alf-ag178",col= "red")
> pacf(vt,lag.max=30,main="residuals for alf-ag178 case",col="red")

